import type { Metadata } from "next";
import { Onest } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/navbar";
import Footer from "@/components/shared/footer";
import { Toaster } from "@/components/ui/sonner";

const onest = Onest({
	variable: "--font-onest",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Steadfast task",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${onest.variable} antialiased`}>
				<main>
					<Navbar />
					{children}
					<Footer />
				</main>
				<Toaster />
			</body>
		</html>
	);
}
